In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [3]:
## Lets creaye synthetic data points
from sklearn.datasets import make_classification


In [5]:
x,y = make_classification(n_samples = 1000, n_features = 2, n_classes = 2, n_clusters_per_class = 1, n_redundant= 0)

In [6]:
x

array([[-0.79571393, -0.69431866],
       [-1.41899719, -1.32430648],
       [-0.41711845, -1.14589122],
       ...,
       [-2.17705275, -0.56486864],
       [ 0.93279952, -1.77472445],
       [ 0.27473437, -2.22765931]])

In [7]:
y

array([0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,

In [9]:
pd.DataFrame(x)[0]

0     -0.795714
1     -1.418997
2     -0.417118
3      0.782427
4     -0.477183
         ...   
995   -1.610633
996   -1.560461
997   -2.177053
998    0.932800
999    0.274734
Name: 0, Length: 1000, dtype: float64

In [12]:
sns.scatterplot(pd.DataFrame(x)[0],pd.DataFrame(x)[1], hue = y)

TypeError: scatterplot() takes from 0 to 1 positional arguments but 2 positional arguments (and 1 keyword-only argument) were given

In [15]:
from sklearn.model_selection import train_test_split
x_train, x_test,y_train, y_test = train_test_split(x,y,test_size=0.25, random_state=42)

In [13]:
from sklearn.svm import SVC

In [14]:
svc = SVC(kernel='linear')

In [16]:
svc.fit(x_train,y_train)

SVC(kernel='linear')

In [17]:
## prediction
y_pred = svc.predict(x_test)

In [37]:
svc.coef_

array([[ 1.6659517 , -0.65821474]])

In [18]:
from sklearn.metrics import classification_report, confusion_matrix

In [20]:
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.95      0.78      0.86       134
           1       0.79      0.95      0.86       116

    accuracy                           0.86       250
   macro avg       0.87      0.87      0.86       250
weighted avg       0.87      0.86      0.86       250

[[105  29]
 [  6 110]]


In [21]:
rbf = SVC(kernel = 'rbf')

In [23]:
rbf.fit(x_train, y_train)

SVC()

In [24]:
y_pred1 = rbf.predict(x_test)

In [25]:
print(classification_report(y_test,y_pred1))
print(confusion_matrix(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.81      0.88       134
           1       0.82      0.96      0.88       116

    accuracy                           0.88       250
   macro avg       0.89      0.89      0.88       250
weighted avg       0.89      0.88      0.88       250

[[109  25]
 [  5 111]]


In [28]:
polynomial = SVC(kernel = 'poly')
polynomial.fit(x_train, y_train)
y_pred2 = polynomial.predict(x_test)
print(classification_report(y_test,y_pred2))
print(confusion_matrix(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.87      0.89      0.88       134
           1       0.87      0.84      0.86       116

    accuracy                           0.87       250
   macro avg       0.87      0.87      0.87       250
weighted avg       0.87      0.87      0.87       250

[[119  15]
 [ 18  98]]


In [29]:
sigmoid = SVC(kernel = 'sigmoid')
sigmoid.fit(x_train, y_train)
y_pred3 = sigmoid.predict(x_test)
print(classification_report(y_test,y_pred3))
print(confusion_matrix(y_test,y_pred3))

              precision    recall  f1-score   support

           0       0.89      0.81      0.85       134
           1       0.80      0.89      0.84       116

    accuracy                           0.84       250
   macro avg       0.85      0.85      0.84       250
weighted avg       0.85      0.84      0.84       250

[[108  26]
 [ 13 103]]


In [36]:
sigmoid.intercept_

array([0.7920485])

## HyperParameter Tuning with SVC

In [30]:
from sklearn.model_selection import GridSearchCV
param_grid = {'C' : [0.1,1,10,100,1000],
              'gamma': [1,0.1,0.01,0.001],
              'kernel' : ['rbf']}

In [32]:
grid = GridSearchCV(SVC(),param_grid= param_grid,refit=True,cv = 5, verbose = 3)

In [33]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.920 total time=   0.1s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.873 total time=   0.0s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.900 total time=   0.2s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.887 total time=   0.3s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.887 total time=   0.2s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.893 total time=   0.1s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.867 total time=   0.1s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.880 total time=   0.0s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.887 total time=   0.0s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.880 total time=   0.0s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.913 total time=   0.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001], 'kernel': ['rbf']},
             verbose=3)

In [34]:
grid.best_params_

{'C': 100, 'gamma': 1, 'kernel': 'rbf'}

In [35]:
y_pred4 = grid.predict(x_test)
print(classification_report(y_test, y_pred4))
print(confusion_matrix(y_test,y_pred4))

              precision    recall  f1-score   support

           0       0.95      0.85      0.90       134
           1       0.85      0.95      0.89       116

    accuracy                           0.90       250
   macro avg       0.90      0.90      0.90       250
weighted avg       0.90      0.90      0.90       250

[[114  20]
 [  6 110]]


In [40]:
import seaborn as sns
df = sns.load_dataset('tips')

In [41]:
df.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [42]:
df.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype   
---  ------      --------------  -----   
 0   total_bill  244 non-null    float64 
 1   tip         244 non-null    float64 
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64   
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB


In [44]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [45]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [48]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [49]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [50]:
## feature encoding (label encoding and onehot encoding)

In [52]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [51]:
## independent and dependent features

In [55]:
a = df[['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']]
b = df['total_bill']

In [56]:
## train test split
from sklearn.model_selection import train_test_split
a_train,a_test,b_train,b_test = train_test_split(a,b,test_size = 0.25, random_state = 42)

In [58]:
a_train.head()

total_bill   tip     sex smoker  day    time  size
115       17.31  3.50  Female     No  Sun  Dinner     2
181       23.33  5.65    Male    Yes  Sun  Dinner     2
225       16.27  2.50  Female    Yes  Fri   Lunch     2
68        20.23  2.01    Male     No  Sat  Dinner     2
104       20.92  4.08  Female     No  Sat  Dinner     2

In [59]:
## Feature Encoding (Label Encoding and OneHotEncoding)

In [60]:
from sklearn.preprocessing import LabelEncoder

In [61]:
le1 = LabelEncoder()
le2 = LabelEncoder()
le3 = LabelEncoder()

In [62]:
a_train['sex'] = le1.fit_transform(a_train['sex'])
a_train['smoker'] = le2.fit_transform(a_train['smoker'])
a_train['time'] = le3.fit_transform(a_train['time'])

In [63]:
a_train.head()

total_bill   tip  sex  smoker  day  time  size
115       17.31  3.50    0       0  Sun     0     2
181       23.33  5.65    1       1  Sun     0     2
225       16.27  2.50    0       1  Fri     1     2
68        20.23  2.01    1       0  Sat     0     2
104       20.92  4.08    0       0  Sat     0     2

In [64]:
a_test['sex'] = le1.transform(a_test['sex'])
a_test['smoker'] = le2.transform(a_test['smoker'])
a_test['time'] = le3.transform(a_test['time'])

In [65]:
a_test.head()

total_bill   tip  sex  smoker   day  time  size
24        19.82  3.18    1       0   Sat     0     2
6          8.77  2.00    1       0   Sun     0     2
153       24.55  2.00    1       0   Sun     0     4
211       25.89  5.16    1       1   Sat     0     4
198       13.00  2.00    0       1  Thur     1     2

In [66]:
## onehotEncodinh
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [75]:
ct = ColumnTransformer(transformers = [('onehot',OneHotEncoder(drop='first'),[3])],remainder = 'passthrough')

In [76]:
ct.fit_transform(a_train)


array([[0.0, 17.31, 3.5, ..., 'Sun', 0, 2],
       [1.0, 23.33, 5.65, ..., 'Sun', 0, 2],
       [1.0, 16.27, 2.5, ..., 'Fri', 1, 2],
       ...,
       [1.0, 5.75, 1.0, ..., 'Fri', 0, 2],
       [1.0, 34.63, 3.55, ..., 'Sun', 0, 2],
       [1.0, 44.3, 2.5, ..., 'Sat', 0, 3]], dtype=object)

In [77]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)
a_train = ct.fit_transform(a_train)

In [78]:
a_test = ct.transform(a_test)

In [79]:
a_test

array([[0.0, 19.82, 3.18, 1, 'Sat', 0, 2],
       [0.0, 8.77, 2.0, 1, 'Sun', 0, 2],
       [0.0, 24.55, 2.0, 1, 'Sun', 0, 4],
       [1.0, 25.89, 5.16, 1, 'Sat', 0, 4],
       [1.0, 13.0, 2.0, 0, 'Thur', 1, 2],
       [1.0, 17.89, 2.0, 1, 'Sun', 0, 2],
       [1.0, 28.44, 2.56, 1, 'Thur', 1, 2],
       [0.0, 12.48, 2.52, 0, 'Thur', 1, 2],
       [0.0, 14.78, 3.23, 1, 'Sun', 0, 2],
       [1.0, 15.38, 3.0, 0, 'Fri', 0, 2],
       [0.0, 18.29, 3.0, 1, 'Sun', 0, 2],
       [0.0, 10.77, 1.47, 1, 'Sat', 0, 2],
       [0.0, 10.65, 1.5, 0, 'Thur', 1, 2],
       [1.0, 14.48, 2.0, 1, 'Sun', 0, 2],
       [0.0, 10.07, 1.83, 0, 'Thur', 1, 1],
       [0.0, 18.64, 1.36, 0, 'Thur', 1, 3],
       [1.0, 18.71, 4.0, 1, 'Thur', 1, 3],
       [0.0, 21.58, 3.92, 1, 'Sun', 0, 2],
       [0.0, 16.45, 2.47, 0, 'Sat', 0, 2],
       [0.0, 41.19, 5.0, 1, 'Thur', 1, 5],
       [0.0, 20.69, 2.45, 0, 'Sat', 0, 4],
       [0.0, 20.65, 3.35, 1, 'Sat', 0, 3],
       [1.0, 14.31, 4.0, 0, 'Sat', 0, 2],
       [0.0, 9.5

In [80]:
## Support Vector Regresion 
from sklearn.svm import SVR
svr = SVR()


In [81]:
svr.fit(a_train,b_train)

ValueError: could not convert string to float: 'Sun'

In [82]:
b_pred = svr.predict(a_test)

NotFittedError: This SVR instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.

In [ ]:
from sklearn.metrics import r2_score, mean_absolute_error
print(r2_score(b_test,b_pred))