In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline


In [34]:
df = pd.read_csv("Algerian_forest_fires_dataset_CLEANED.csv")

In [35]:
df.head()

day  month  year  Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  \
0    1      6  2012           29  57  18   0.0  65.7  3.4   7.6  1.3  3.4   
1    2      6  2012           29  61  13   1.3  64.4  4.1   7.6  1.0  3.9   
2    3      6  2012           26  82  22  13.1  47.1  2.5   7.1  0.3  2.7   
3    4      6  2012           25  89  13   2.5  28.6  1.3   6.9  0.0  1.7   
4    5      6  2012           27  77  16   0.0  64.8  3.0  14.2  1.2  3.9   

   FWI      Classes  Region  
0  0.5  not fire          0  
1  0.4  not fire          0  
2  0.1  not fire          0  
3  0.0  not fire          0  
4  0.5  not fire          0

In [36]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [37]:
df.drop(["day", "month", "year"], axis = 1, inplace=True)

In [38]:
df.head()

Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  FWI      Classes  \
0           29  57  18   0.0  65.7  3.4   7.6  1.3  3.4  0.5  not fire      
1           29  61  13   1.3  64.4  4.1   7.6  1.0  3.9  0.4  not fire      
2           26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1  not fire      
3           25  89  13   2.5  28.6  1.3   6.9  0.0  1.7  0.0  not fire      
4           27  77  16   0.0  64.8  3.0  14.2  1.2  3.9  0.5  not fire      

   Region  
0       0  
1       0  
2       0  
3       0  
4       0

In [39]:
df['Classes'].value_counts()

Classes
fire             131
not fire         101
fire               4
fire               2
not fire           2
not fire           1
not fire           1
not fire           1
Name: count, dtype: int64

In [40]:
## Encoding 
df['Classes'] = np.where(df['Classes'].str.contains('not fire'), 0,1)

In [41]:
df.head()

Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  FWI  Classes  Region
0           29  57  18   0.0  65.7  3.4   7.6  1.3  3.4  0.5        0       0
1           29  61  13   1.3  64.4  4.1   7.6  1.0  3.9  0.4        0       0
2           26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1        0       0
3           25  89  13   2.5  28.6  1.3   6.9  0.0  1.7  0.0        0       0
4           27  77  16   0.0  64.8  3.0  14.2  1.2  3.9  0.5        0       0

In [42]:
df.tail()

Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  FWI  Classes  \
238           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9  6.5        1   
239           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2  0.0        0   
240           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4  0.2        0   
241           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1  0.7        0   
242           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8  0.5        0   

     Region  
238       1  
239       1  
240       1  
241       1  
242       1

In [43]:
df['Classes'].value_counts()

Classes
1    137
0    106
Name: count, dtype: int64

In [44]:
## dividing features into dependend and independent features
X = df.drop("FWI", axis = 1)
y = df['FWI']

In [45]:
X

Temperature  RH  Ws  Rain  FFMC   DMC    DC  ISI   BUI  Classes  Region
0             29  57  18   0.0  65.7   3.4   7.6  1.3   3.4        0       0
1             29  61  13   1.3  64.4   4.1   7.6  1.0   3.9        0       0
2             26  82  22  13.1  47.1   2.5   7.1  0.3   2.7        0       0
3             25  89  13   2.5  28.6   1.3   6.9  0.0   1.7        0       0
4             27  77  16   0.0  64.8   3.0  14.2  1.2   3.9        0       0
..           ...  ..  ..   ...   ...   ...   ...  ...   ...      ...     ...
238           30  65  14   0.0  85.4  16.0  44.5  4.5  16.9        1       1
239           28  87  15   4.4  41.1   6.5   8.0  0.1   6.2        0       1
240           27  87  29   0.5  45.9   3.5   7.9  0.4   3.4        0       1
241           24  54  18   0.1  79.7   4.3  15.2  1.7   5.1        0       1
242           24  64  15   0.2  67.3   3.8  16.5  1.2   4.8        0       1

[243 rows x 11 columns]

In [46]:
y

0      0.5
1      0.4
2      0.1
3      0.0
4      0.5
      ... 
238    6.5
239    0.0
240    0.2
241    0.7
242    0.5
Name: FWI, Length: 243, dtype: float64

In [47]:
## train test split
from sklearn.model_selection import train_test_split
X_train, X_test,y_train , y_test = train_test_split(X,y, test_size=0.25, random_state= 45)

In [48]:
X_train.shape, X_test.shape

((182, 11), (61, 11))

In [49]:
## Feature selection on basis of correlation
X_train.corr()

Temperature        RH        Ws      Rain      FFMC       DMC  \
Temperature     1.000000 -0.660795 -0.278939 -0.370676  0.686037  0.489583   
RH             -0.660795  1.000000  0.229917  0.232069 -0.650166 -0.410087   
Ws             -0.278939  0.229917  1.000000  0.274892 -0.170338 -0.015730   
Rain           -0.370676  0.232069  0.274892  1.000000 -0.549174 -0.277992   
FFMC            0.686037 -0.650166 -0.170338 -0.549174  1.000000  0.591452   
DMC             0.489583 -0.410087 -0.015730 -0.277992  0.591452  1.000000   
DC              0.377292 -0.228161  0.080056 -0.289827  0.496276  0.881988   
ISI             0.625153 -0.705548 -0.015707 -0.339779  0.746234  0.671494   
BUI             0.461357 -0.354014  0.024178 -0.289332  0.579781  0.982540   
Classes         0.531519 -0.437177 -0.106463 -0.364482  0.768765  0.560499   
Region          0.303753 -0.427609 -0.249133 -0.087988  0.245305  0.210788   

                   DC       ISI       BUI   Classes    Region  
Temperature  0.377292  0.625153  0.461357  0.531519  0.303753  
RH          -0.228161 -0.705548 -0.354014 -0.437177 -0.427609  
Ws           0.080056 -0.015707  0.024178 -0.106463 -0.249133  
Rain        -0.289827 -0.339779 -0.289332 -0.364482 -0.087988  
FFMC         0.496276  0.746234  0.579781  0.768765  0.245305  
DMC          0.881988  0.671494  0.982540  0.560499  0.210788  
DC           1.000000  0.494381  0.943979  0.485457 -0.051156  
ISI          0.494381  1.000000  0.633688  0.726887  0.295307  
BUI          0.943979  0.633688  1.000000  0.562938  0.110407  
Classes      0.485457  0.726887  0.562938  1.000000  0.179664  
Region      -0.051156  0.295307  0.110407  0.179664  1.000000

In [50]:
## check for multicollinearity
plt.figure(figsize=(12,10))
corr = X_train.corr()
sns.heatmap(corr, annot=True)

<Axes: >

In [51]:
def correlation(dataset , threshold):
    col_corr = set()
    corr_matrix = dataset.corr()
    for i in  range (len(corr_matrix.columns)):
        for j in range(i):
            if abs(corr_matrix.iloc[i,j]) > threshold:
                colname = corr_matrix.columns[i]
                col_corr.add(colname)
    return col_corr

In [52]:
corr_features = correlation(X_train, 0.85)

In [53]:
corr_features


{'BUI', 'DC'}

In [54]:
## drop features when correlation is more than 0.85
X_train.drop(corr_features, axis=1, inplace=True)
X_test.drop(corr_features, axis=1, inplace=True)

In [55]:
X_train.shape, X_test.shape

((182, 9), (61, 9))

In [56]:
## Feature Scaling or Standardization
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_Scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [57]:
X_train_Scaled

array([[ 1.03973391,  0.00396204,  0.21039187, ...,  0.54677005,
         0.85634884,  1.01105006],
       [-0.03239964, -0.97934302, -0.52597966, ..., -0.71718494,
        -1.16774842, -0.98907071],
       [-0.30043303, -0.45491366, -1.63053696, ...,  0.15786082,
         0.85634884, -0.98907071],
       ...,
       [-0.56846642, -1.37266504, -0.1577939 , ...,  0.88706562,
         0.85634884,  1.01105006],
       [ 1.57580069, -1.2415577 , -0.89416543, ..., -0.15812793,
         0.85634884,  1.01105006],
       [ 1.3077673 , -0.586021  , -0.52597966, ...,  0.78983831,
         0.85634884,  1.01105006]])

In [58]:
X_test_scaled

array([[ 5.03667137e-01, -1.30711137e+00,  5.78577631e-01,
        -3.18484456e-01,  7.14407284e-01,  6.56863671e-01,
         3.46358924e+00,  8.56348839e-01,  1.01105006e+00],
       [-3.00433029e-01, -5.20467329e-01, -1.63053696e+00,
        -3.66191593e-01,  2.83576068e-01, -7.00598078e-01,
        -5.47037153e-01, -1.16774842e+00, -9.89070710e-01],
       [-3.00433029e-01,  3.97284058e-01, -5.25979664e-01,
        -3.66191593e-01,  5.16088153e-01, -2.30114176e-01,
        -3.65937939e-02,  8.56348839e-01, -9.89070710e-01],
       [ 7.71700526e-01, -1.92698976e-01,  5.78577631e-01,
        -3.66191593e-01,  6.52859967e-01, -2.18672035e-02,
         5.22463219e-01,  8.56348839e-01, -9.89070710e-01],
       [ 1.30776730e+00, -1.70043340e+00, -8.94165429e-01,
        -7.99487729e-02,  5.70796879e-01,  2.17231173e-01,
         1.20198593e-02,  8.56348839e-01,  1.01105006e+00],
       [ 7.71700526e-01, -7.17128340e-01, -8.94165429e-01,
        -2.23070183e-01,  2.35705932e-01,  3.983560

## boxplot to understand Effect of Standard scaler

In [59]:
plt.subplots(figsize= (15,5))
plt.subplot(1,2,1)
sns.boxplot(data = X_train)
plt.title("X_train Before Scaling")
plt.subplot(1,2,2)
sns.boxplot(data = X_train_Scaled)
plt.title("X_train after scaling")

Text(0.5, 1.0, 'X_train after scaling')

## Linear Regression Model


In [60]:
from sklearn.linear_model import LinearRegression
linReg = LinearRegression()

In [61]:

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
linreg = LinearRegression()
linreg.fit(X_train_Scaled, y_train)
y_pred = linreg.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)
score = r2_score(y_test, y_pred)
print("mean Absolute error ", mae)
print("r2 Score as", score)
plt.scatter(y_test,y_pred)

mean Absolute error  0.7713645614904542
r2 Score as 0.9096193210066799


## Lasso Regression 

In [62]:

from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
lasso = Lasso()
lasso.fit(X_train_Scaled, y_train)
y_pred = lasso.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)
score = r2_score(y_test, y_pred)
print("mean Absolute error ", mae)
print("r2 Score as", score)
plt.scatter(y_test,y_pred)

mean Absolute error  1.1873366121992208
r2 Score as 0.9153377261039456


## Ridge Regression Model


In [63]:

from sklearn.linear_model import Ridge
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
rid = Ridge()
rid.fit(X_train_Scaled, y_train)
y_pred = rid.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)
score = r2_score(y_test, y_pred)
print("mean Absolute error ", mae)
print("r2 Score as", score)
plt.scatter(y_test,y_pred)

mean Absolute error  0.7619995110582065
r2 Score as 0.9123601798432845


## Elastic Net Regression Model


In [64]:

from sklearn.linear_model import ElasticNet
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score
Elastic = ElasticNet()
Elastic.fit(X_train_Scaled, y_train)
y_pred = Elastic.predict(X_test_scaled)
mae = mean_absolute_error(y_test, y_pred)
score = r2_score(y_test, y_pred)
print("mean Absolute error ", mae)
print("r2 Score as", score)
plt.scatter(y_test,y_pred)

mean Absolute error  1.7157737929202217
r2 Score as 0.8844387249095774


## Cross Validation Model


In [65]:
from sklearn.linear_model import LassoCV
lassocv = LassoCV()
lassocv.fit(X_train_Scaled, y_train)

LassoCV()

In [66]:
lassocv.alphas

In [67]:
lassocv.alphas_

array([7.09297065, 6.61492817, 6.16910415, 5.75332717, 5.36557218,
       5.00395057, 4.66670105, 4.35218102, 4.05885858, 3.7853051 ,
       3.53018821, 3.29226534, 3.07037767, 2.86344449, 2.67045792,
       2.49047799, 2.32262811, 2.16609075, 2.02010348, 1.88395527,
       1.75698299, 1.63856822, 1.5281342 , 1.42514307, 1.3290932 ,
       1.23951676, 1.15597748, 1.07806847, 1.00541026, 0.93764898,
       0.87445457, 0.81551926, 0.76055599, 0.70929706, 0.66149282,
       0.61691041, 0.57533272, 0.53655722, 0.50039506, 0.46667011,
       0.4352181 , 0.40588586, 0.37853051, 0.35301882, 0.32922653,
       0.30703777, 0.28634445, 0.26704579, 0.2490478 , 0.23226281,
       0.21660907, 0.20201035, 0.18839553, 0.1756983 , 0.16385682,
       0.15281342, 0.14251431, 0.13290932, 0.12395168, 0.11559775,
       0.10780685, 0.10054103, 0.0937649 , 0.08744546, 0.08155193,
       0.0760556 , 0.07092971, 0.06614928, 0.06169104, 0.05753327,
       0.05365572, 0.05003951, 0.04666701, 0.04352181, 0.04058

In [68]:
lassocv.mse_path_

array([[68.94264817, 94.96565083, 47.19676599, 41.33277872, 31.84725423],
       [64.32256179, 94.96565083, 42.12761595, 35.76708914, 28.09323664],
       [57.88328842, 94.96565083, 37.70177774, 30.94896234, 24.79605915],
       [52.22327577, 87.44524513, 33.71269286, 26.77698902, 21.37061933],
       [47.24503184, 77.99616764, 29.57901888, 23.16577473, 18.41342565],
       [42.86349296, 69.77386744, 25.97676688, 20.04114237, 15.8617615 ],
       [37.80469833, 62.61882342, 22.83708624, 17.33855984, 13.66179498],
       [33.22014855, 55.24483812, 20.10017309, 15.00206878, 11.76623904],
       [29.22322453, 48.59878275, 17.713983  , 12.98308263, 10.13423992],
       [25.73767118, 42.79938551, 15.63298193, 11.23927025,  8.73034635],
       [22.69750407, 37.73716545, 13.81826431,  9.73400971,  7.52380027],
       [20.04529152, 33.31836388, 12.23524126,  8.43545984,  6.48792046],
       [17.73056993, 29.45975578, 10.85404918,  7.31597868,  5.59941737],
       [15.71083384, 26.08941028,  9.6

In [69]:
## pickling the machine learning models, preprocessing model standardiser

In [72]:
scaler

StandardScaler()

In [70]:
rid

Ridge()

In [75]:
import pickle
pickle.dump(scaler,open('scaler.pkl', 'wb'))
pickle.dump(rid,open('ridge.pkl', 'wb'))