## Numpy 
Numpy is a fundamental library for scientific computing in python. It provides supports for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of NumPy,focusing on arrays and vectorized operations.'

In [2]:
import numpy as np
## Create Arrays using Numpy
## creating an 1-Dimension Array
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(type(arr_1))
print(arr_1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [3]:
arr_2 = np.array([1,2,5,4,5,])
arr_2.reshape((1,5))

array([[1, 2, 5, 4, 5]])

In [6]:
## arrays with inbuilt function
np.arange(0,10,2).reshape(1,5)

array([[0, 2, 4, 6, 8]])

In [7]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:

np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
## identity matrix - diagonal element would be 1
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
##attributes of an 2d array usinng numpy
arr = np.array([[1,2,3],[4,5,6]])
print("Array:\n", arr)
print("Shape: ", arr.shape)
print("Number of Dimensions:", arr.size)
print("Size(number of elements):",arr.size)
print("Data type", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimensions: 6
Size(number of elements): 6
Data type int32
Item size (in bytes):  4


In [15]:
### Numpy vectorization Operations
arr_1 = np.array([1,2,3,4,5])
arr_2 = np.array([10,20,30,40,50])

##Element Wise Addition
print("Addition: ", arr_1 + arr_2)
 
## Element wise subtraction
print("Subtraction: ", arr_1-arr_2)

##Element wise multiplication
print("Multiplication: ", arr_1*arr_2)

##Element wise division
print("Division: ", arr_1 / arr_2)

Addition:  [11 22 33 44 55]
Subtraction:  [ -9 -18 -27 -36 -45]
Multiplication:  [ 10  40  90 160 250]
Division:  [0.1 0.1 0.1 0.1 0.1]


In [16]:
## universal functions
arr = np.array([2,3,4,5,6])
##square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))
 
## sine
print(np.sin(arr))
 
## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [19]:
## Slicing Operations and Array Indexing
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print("Array is : \n: ",arr)


Array is : 
:  [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [23]:
new_Arr = [arr[0][0], arr[0][1], arr[0][2],arr[0][3]]
print(new_Arr)

[1, 2, 3, 4]


In [26]:
## to get 14 number in the arr
arr[2][3]

14

In [30]:
print(arr[1:])

[[ 6  7  8  9 10]
 [11 12 13 14 15]]


In [31]:
print(arr[1:1:3])

[]


In [29]:
print(arr[0][0])
print(arr[0:2:2])

1
[[1 2 3 4 5]]


In [32]:
## Modify array elements
arr[0,0] = 100
print(arr)

[[100   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  12  13  14  15]]


In [33]:
arr[1:] = 100
print(arr)

[[100   2   3   4   5]
 [100 100 100 100 100]
 [100 100 100 100 100]]


In [35]:
### Practical example
### statistical concepts -- Normalization
## to have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])
## calculating the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
## Normalize the data
normalized_Data = (data - mean) / std_dev
print("Normalized Data:", normalized_Data)

Normalized Data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
## calculate the mean, median ,mode,SD and variance


In [41]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>5) & (data < 9)]

array([6, 7, 8])