In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import DBSCAN
from sklearn.datasets import make_moons
%matplotlib inline

In [3]:
x,y = make_moons(n_samples = 250, noise = 0.05)

In [4]:
x

array([[ 1.22378236e-01,  1.15735434e-01],
       [ 1.99956426e+00,  3.31516068e-01],
       [ 5.48820990e-01, -3.12016314e-01],
       [ 3.75123903e-01, -2.29504162e-01],
       [ 2.02651472e+00,  2.48960009e-01],
       [ 4.00525362e-01, -2.49106156e-01],
       [-1.11506783e-01,  1.05302382e+00],
       [ 2.00772160e+00,  3.79987885e-01],
       [ 8.15244568e-01, -4.85540497e-01],
       [ 1.01227306e+00, -4.24518915e-01],
       [ 1.81941231e+00, -3.77610001e-02],
       [-6.13235544e-01,  8.09858316e-01],
       [ 2.00485823e+00,  1.55924021e-01],
       [ 9.87125899e-01,  9.55481904e-02],
       [-9.86885086e-01, -8.45733260e-03],
       [ 3.72190666e-01,  9.50229020e-01],
       [ 7.25198494e-01,  7.53755385e-01],
       [ 1.03316215e+00,  6.36901888e-02],
       [ 5.23051898e-01,  8.86104742e-01],
       [ 4.31657653e-01, -3.53920160e-01],
       [ 7.04370303e-01, -4.40480161e-01],
       [ 1.28307802e+00, -4.41172024e-01],
       [-1.01378192e+00,  2.81678708e-01],
       [ 1.

In [5]:
y

array([1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [7]:
plt.scatter(x[:,0], x[:,1], c = y)

In [8]:
## feature scaling (standard Scaling)
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()


In [9]:
x_scaled = scaler.fit_transform(x)

In [10]:
x_scaled

array([[-4.39847260e-01, -2.69865024e-01],
       [ 1.71001930e+00,  1.64322063e-01],
       [ 4.85406821e-02, -1.13057380e+00],
       [-1.50387690e-01, -9.64545412e-01],
       [ 1.74088459e+00, -1.79467283e-03],
       [-1.21296408e-01, -1.00398793e+00],
       [-7.07706478e-01,  1.61611755e+00],
       [ 1.71936159e+00,  2.61855548e-01],
       [ 3.53665020e-01, -1.47973377e+00],
       [ 5.79313926e-01, -1.35694804e+00],
       [ 1.50369844e+00, -5.78725779e-01],
       [-1.28231649e+00,  1.12682747e+00],
       [ 1.71608228e+00, -1.88998798e-01],
       [ 5.50513879e-01, -3.10485168e-01],
       [-1.71024247e+00, -5.19761850e-01],
       [-1.53747009e-01,  1.40927704e+00],
       [ 2.50538830e-01,  1.01393890e+00],
       [ 6.03237372e-01, -3.74588849e-01],
       [ 1.90283654e-02,  1.28024816e+00],
       [-8.56418319e-02, -1.21489142e+00],
       [ 2.26685130e-01, -1.38906476e+00],
       [ 8.89456088e-01, -1.39045690e+00],
       [-1.74104635e+00,  6.40408754e-02],
       [ 7.

In [11]:
dbscan = DBSCAN(eps = 0.3)

In [12]:
dbscan.fit(x_scaled)

DBSCAN(eps=0.3)

In [13]:
dbscan.labels_

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1], dtype=int64)

In [14]:
plt.scatter(x[:,0], x[:,1], c = dbscan.labels_)

In [15]:
plt.scatter(x[:,0], x[:,1], c = y)